export const REMOVE_NOTE_ACTION = 'remove'
export const ADD_UPDATE_NOTE_ACTION = 'update'
export const COPY_NOTE_ACTION = 'copy'
export const COLOR_NOTE_ACTION = 'color'
export const img_NOTE_ACTION = 'img'
export const EMPTY_STR = ''
